version: "3.8"

services:
  nodeserver:
    build:
      context: ./application
    ports:
      - "5002:5002"
    volumes:
      - shared-volume:/usr/src/app/videos
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3030:80"
    volumes:
      # - ./nginx/examples/videos:/opt/static/videos
      - ./nginx/examples/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - shared-volume:/opt/static/videos
  frontend:
    build:
      context: ./streaming-frontend
    ports:
      - "8080:8080"

volumes:
  shared-volume:
    # volumes:
    #   db:
    #     driver: local
